### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by alphapapa** [jcs090218/line-reminder#1]
Hi,

Here are a few suggestions:

1.  I see in your code that you use several functions to get the current line number, including converting a string to an integer.  Instead you can simply call `(line-number-at-pos (point))`, `(line-number-at-pos (point-max))`, etc.  :)  You should also do that here instead of using `goto-char` back and forth: https://github.com/jcs090218/line-reminder/blob/master/line-reminder.el#L276 and https://github.com/jcs090218/line-reminder/blob/master/line-reminder.el#L327.

2.  At https://github.com/jcs090218/line-reminder/blob/master/line-reminder.el#L163, you can use `cl-case` with implicit returns instead of `let` and `cond` and `string=`, e.g.:

```el
(defun line-reminder-propertized-sign-by-type (type &optional line-number)
  "Return a propertized sign string by type.
TYPE : type of the propertize sign you want.
LINE-NUMBER : Pass is line number for normal sign."
  (cl-case type
    ('normal (if (not line-number)
                 (error "Normal line but with no line number pass in")
               ;; Just return normal linum format.
               (line-reminder-get-propertized-normal-sign line-number)))
    ('modified (line-reminder-get-propertized-modified-sign))
    ('saved (line-reminder-get-propertized-saved-sign))))
```

3.  The functions ` line-reminder-is-contain-list-string` and `line-reminder-is-contain-list-integer` can probably be replaced by `member`.

4.  The functions `line-reminder-linum-format-string-align-right`, `line-reminder-get-current-line-string`, `line-reminder-get-propertized-modified-sign`, and `line-reminder-get-propertized-saved-sign` seem to be used in only one place.  So you should probably either inline them yourself, or use `defsubst` instead of `defun`.  I guess that since this code runs on every buffer change, you will want to reduce function-call overhead as much as possible to increase performance.

    Generally, if a piece of code is only used in one place, and it is a small piece of code, it shouldn't be in its own function.  You can use `defsubst` to automatically inline it, or you can use `cl-macrolet` to make a function-local alias to organize your code more clearly.

5.  `line-reminder-get-file-name` seems to be unused.  This kind of error should be caught when you byte-compile the file.

**Comment by jcs090218** [comment]
Okay I applied most of the suggestion except the 3rd point. I am still having trouble implementing that. I will close this issue for now. I will still consider this implementation in the future version. Thank you for your suggestions, is very helpful!
